# Generated by Django 2.2.6 on 2020-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
