# Generated by Django 2.2.6 on 2020-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0003_auto_20201005_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_field',
            name='video_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
