# Generated by Django 2.2.6 on 2021-11-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0004_auto_20201011_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='w_link',
        ),
    ]
